apiVersion: 1

datasources:
  - name: Elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "car-erp-logs-*"
    isDefault: true
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      logMessageField: "log_message"
      logLevelField: "level"
      maxConcurrentShardRequests: 5
    editable: false
